feat: update readme
neutralinojs-community/node-neutralino pull request #17
Opened 2024-08-16 15:48 UTC by viralgupta

closes #16

2024-08-17 06:35 UTC, shalithasuranga commented on README.md
> +> // This is required since node-neutralino communicates via neutralinojs extension protocol.
Could you please use `js` for code highlighting. Now, GitHub renders some lines in red since they are not valid JSON statements. Thanks

2024-08-17 06:38 UTC, shalithasuranga commented on README.md
> +  - Take input from users for all the [supported args](https://github.com/neutralinojs-community/node-neutralino/blob/main/types/api/window.ts).
This link is broken. Please check

2024-08-17 06:41 UTC, shalithasuranga requested changes
Hello @viralgupta, thanks so much for sending this PR. Please check the inline notes and make sure to improve the markdown formatting by following [this guide](https://google.github.io/styleguide/docguide/style.html) Thanks :tada:

2024-08-17 10:20 UTC, viralgupta commented
@shalithasuranga thank you sir for reviewing the PR, I have updated the PR with the requested changes, added TOC, and fixed some formatting issues.

Please let me know if there are any specify formatting issues I missed. 😇

2024-08-19 06:50 UTC, shalithasuranga approved these changes
Thanks for sending these updates. Looks great now :tada:

2024-08-19 06:50 UTC, merged